// expots table
module.exports = (dbinfo, Sequelize) => {
    return dbinfo.define(
        // The name of the model. The model will be stored in `sequelize.models` under this name Arelier.
        "tbl_atelier",
        {
            // field name
            id: {
                // set data type
                type: Sequelize.DataTypes.INTEGER,
                // set primerKey
                primaryKey: true,
                // autoIncrement can be used to create auto_incrementing integer columns
                autoIncrement: true
            },
            nom: {
                //set data type with max length
                type: Sequelize.DataTypes.STRING(45),
                // setting allowNull to false will add NOT NULL to the column, which means an error will be if you add info in this coulimn
                allowNull: false
            },
        },
        {
            /**
             * By default, Sequelize will add the attributes createdAt and updatedAt to your model so you will be able to know when the database entry went into the db and when it was updated last.
             */
            timestamps: true,
            /**
             * Sequelize allow setting underscored option for Model. When true this option will set the field option on all attributes to the underscored version of its name.
             * This also applies to foreign keys generated by associations.
             * */

            underscored: true
        }
    );
};

